--- 跨模块共用常量（prefab 名等）。

--- 青蛙
PREFAB_FROG = "frog"
--- 明眼青蛙
PREFAB_LUNAR_FROG = "lunarfrog"

--- 青蛙雨已开始
STATE_WORLD_FROGRAIN_STARTED = "FROGRAIN_STARTED"
--- 青蛙雨计数表：`{ [PREFAB_FROG]=n, [PREFAB_LUNAR_FROG]=n }`
STATE_WORLD_FROGRAIN_COUNT = "FROGRAIN_COUNT"

--- 青蛙雨
TEXT_FROGRAIN = STRINGS.UI.CUSTOMIZATIONSCREEN.FROGRAIN
